### ISSUE TITLE
ajout avec montage NFS

### ISSUE THREAD

**Issue by aversag** [MicrosoftDocs/sql-docs.fr-fr#104]
bonjour,
cela serait intéressant d'avoir également cette partie. merci

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: ae3bc9b9-65f5-13bb-53c5-ed929a94b638
* Version Independent ID: eccef86a-10ea-2bbb-ab1b-c530b3fb758c
* Content: [Configurer l’envoi de journaux pour SQL Server sur Linux - SQL Server](https://docs.microsoft.com/fr-fr/sql/linux/sql-server-linux-use-log-shipping?view=sql-server-2017#feedback)
* Content Source: [docs/linux/sql-server-linux-use-log-shipping.md](https://github.com/MicrosoftDocs/sql-docs.fr-fr/blob/live/docs/linux/sql-server-linux-use-log-shipping.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @meet-bhagdev
* Microsoft Alias: **meetb**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/sql-docs #2017](https://github.com/MicrosoftDocs/sql-docs/issues/2017) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Bonjour @aversag 

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise. 

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/sql-docs/issues/2017 

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International
