### ISSUE TITLE
Log shipping is not installed on this instance.

### ISSUE THREAD

**Issue by aversag** [MicrosoftDocs/sql-docs.fr-fr#105]
Hello,
I'm getting an error on my centos install:

Msg 32018, Level 16, State 2, Server bdd1, Procedure master.dbo.sp_add_log_shipping_primary_database, Line 182
Log shipping is not installed on this instance.

I've activated the sql agent, so I don't know why it's not working.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: ae3bc9b9-65f5-13bb-53c5-ed929a94b638
* Version Independent ID: eccef86a-10ea-2bbb-ab1b-c530b3fb758c
* Content: [Configurer l’envoi de journaux pour SQL Server sur Linux - SQL Server](https://docs.microsoft.com/fr-fr/sql/linux/sql-server-linux-use-log-shipping?view=sql-server-2017)
* Content Source: [docs/linux/sql-server-linux-use-log-shipping.md](https://github.com/MicrosoftDocs/sql-docs.fr-fr/blob/live/docs/linux/sql-server-linux-use-log-shipping.md)
* Product: **sql**
* Technology: **linux**
* GitHub Login: @meet-bhagdev
* Microsoft Alias: **meetb**

**Comment by CeciAc** [comment]
Hello, @aversag

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
