### ISSUE TITLE
Bad French automatic transalation

### ISSUE THREAD

**Issue by agriffard** [MicrosoftDocs/sql-docs.fr-fr#108]
The automatic translation does not make any sense in French.

There is no Edit button to submit some changes.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: bbe4ef3a-6282-5c51-5810-c6d63f3a0e1b
* Version Independent ID: 6d655e24-fc84-aad0-2422-2451cfb1ad34
* Content: [Qu’est Azure Data Studio - Azure Data Studio](https://docs.microsoft.com/fr-fr/sql/azure-data-studio/what-is?view=sql-server-2017#feedback)
* Content Source: [docs/azure-data-studio/what-is.md](https://github.com/MicrosoftDocs/sql-docs.fr-fr/blob/live/docs/azure-data-studio/what-is.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by CeciAc** [comment]
Hello, @agriffard 
Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English" option on the right which allows you to switch to the English version without having to change the language settings.

Kind regards,
Microsoft DOCS International Team

@nokura
