### ISSUE TITLE
Translation mistake

### ISSUE THREAD

**Issue by embeau** [MicrosoftDocs/sql-docs.fr-fr#111]
There is a mistake in the french translation : 
Un rowstore représente des données organisées logiquement sous la forme d’une table comportant des lignes et des colonnes, et stockées physiquement dans un format de données en colonnes. &lt;-- it's not "en colonnes" but "en lignes" as we talk about rowstore.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 571bf244-1472-286b-d1a8-7db2e54f40a2
* Version Independent ID: bccbd120-47f3-78b7-0cd6-7d4198ea3604
* Content: [Index columnstore : vue d’ensemble - SQL Server](https://docs.microsoft.com/fr-fr/sql/relational-databases/indexes/columnstore-indexes-overview?view=sql-server-2017#feedback)
* Content Source: [docs/relational-databases/indexes/columnstore-indexes-overview.md](https://github.com/MicrosoftDocs/sql-docs.fr-fr/blob/live/docs/relational-databases/indexes/columnstore-indexes-overview.md)
* Product: **sql**
* Technology: **table-view-index**
* GitHub Login: @MikeRayMSFT
* Microsoft Alias: **mikeray**

**Comment by srvbpigh** [comment]
Hello, @embeau
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @embeau
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/fr-fr/sql/relational-databases/indexes/columnstore-indexes-overview?view=sql-server-2017#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
