### ISSUE TITLE
Traduction plus inpirée pour Fonction Inline que Fonction Table incluse

### ISSUE THREAD

**Issue by pelsql** [MicrosoftDocs/sql-docs.fr-fr#117]
Pourquoi ne pas traduire "fonction de Select". L'expression anglaise de "inline table function" laisse entendre que le code de la requête s'intègre à la requête appellante, mais cela n'exprime pas grand chose sur la nature de la fonction.  La notion de "fonction de Select" exprime mieux ce que cela fait: cela retourne des rangées, et donc implicitement une table.  En plus cela veut dire implicitement qu'elle ne se limite qu'à une requête "Select", une des contraintes de la définition des fonctions de tables incluses..  Cela s'exprimerait bien en anglais également "user defined Select function" ou "Select function".

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 71bc28bf-993a-79e3-1a83-b39052bab882
* Version Independent ID: 73350c77-8839-dcd3-af67-9342a49dbf22
* Content: [CREATE FUNCTION (Transact-SQL) - SQL Server](https://docs.microsoft.com/fr-fr/sql/t-sql/statements/create-function-transact-sql?view=sql-server-ver15#feedback)
* Content Source: [docs/t-sql/statements/create-function-transact-sql.md](https://github.com/MicrosoftDocs/sql-docs.fr-fr/blob/live/docs/t-sql/statements/create-function-transact-sql.md)
* Product: **sql**
* Technology: **t-sql**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by srvbpigh** [comment]
Hello, @pelsql
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by pelsql** [comment]
I've made a suggestion for a french translation, that could have a meaning in english too.  My thought is that user-defined inline function carries not much meaning, and translate poorly in french also.  I suggest the term "user-defined select function" which both carries that it must be defined from a single select query and since it returns rows, it is also a table function.

Maurice Pelchat

________________________________
De : srvbpigh <notifications@github.com>
Envoyé : 28 octobre 2019 13:37
À : MicrosoftDocs/sql-docs.fr-fr <sql-docs.fr-fr@noreply.github.com>
Cc : Maurice Pelchat <maurice.pelchat@outlook.com>; Mention <mention@noreply.github.com>
Objet : Re: [MicrosoftDocs/sql-docs.fr-fr] Traduction plus inpirée pour Fonction Inline que Fonction Table incluse (#117)


Hello, @pelsql<https://github.com/pelsql>

Thank you for your feedback.

We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour @pelsql 

Merci pour vos suggestions linguistiques.  

Malheureusement, après révision, notre équipe linguistique a jugé qu’elles ne remplissaient pas nos critères de validation, car [Pas réalisable pour le contexte.]. 
Votre contribution à nos articles est grandement appréciée. Nous vous encourageons donc à continuer d’envoyer vos commentaires à Microsoft.  

Cordialement, 
L’équipe Microsoft DOCS International
