### ISSUE TITLE
Table at top of French page is corrupted - appears as raw markdown

### ISSUE THREAD

**Issue by brunolewin-msft** [MicrosoftDocs/sql-docs.fr-fr#120]
https://docs.microsoft.com/fr-fr/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver15 :

|Plateforme|Téléchargement|Date de publication| Version | |:---|:---|:---|:---| |Windows|Programme d’installation utilisateur (recommandé)
Programme d’installation système
.zip|26 décembre 2019|1.14.1| |macOS|.zip|26 décembre 2019|1.14.1| |Linux|.deb
.rpm
.tar.gz|26 décembre 2019|1.14.1|

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: c383bb21-4e43-3e4a-825a-058da7f052c1
* Version Independent ID: 09acb751-92d3-9f2d-72cd-dcce3d252391
* Content: [Télécharger et installer - Azure Data Studio](https://docs.microsoft.com/fr-fr/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver15)
* Content Source: [docs/azure-data-studio/download-azure-data-studio.md](https://github.com/MicrosoftDocs/sql-docs.fr-fr/blob/live/docs/azure-data-studio/download-azure-data-studio.md)
* Product: **sql**
* Technology: **azure-data-studio**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by srvbpigh** [comment]
Hello, @brunolewin-msft
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
@brunolewin-msft 

Merci pour votre feedback.  

Notre équipe d’ingénieurs a révisé vos suggestions et les a acceptées. Nous avons modifié les articles concernés selon vos suggestions et les avons republiés sur les pages https://docs.microsoft.com/fr-fr/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver15 du site Docs.   

Votre contribution à nos articles est grandement appréciée. Nous vous encourageons donc à continuer d’envoyer vos commentaires à Microsoft.  

Cordialement,  

L’équipe Microsoft DOCS International
