### ISSUE TITLE
Sentence to rephrase: sql-server-linux-troubleshooting-guide.md

### ISSUE THREAD

**Issue by agriffard** [MicrosoftDocs/sql-docs.fr-fr#13]
In https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-troubleshooting-guide

Is it just me or this sentence contains some typos?
`You must escape the $ anytime using the backslash character you are using it in a terminal command/shell script:`

but I don't know exactly what could be the correct one.

**Comment by CeciAc** [comment]
This looks like source issue, assigned to @carolinacmoravia.
I should move this to the en-us repo but I cannot do it on my side. @ishasahni1

**Comment by ishasahni1** [comment]
@agriffard @CeciAc Thank you so much for valuable feedback. The source has been updated and the updated en-us topic is in localization now.
