### ISSUE TITLE
Azure Data Studio & Devops

### ISSUE THREAD

**Issue by Churchill59** [MicrosoftDocs/sql-docs.fr-fr#130]
Well done for this extension. 
Is there a plan to get Data Studio working with Azure Devops and going a step further in the CI/CD process?

Thank you

[Tapez vos commentaires ici]

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: d25be772-12d5-6a8e-1eb5-9982ae0bfcac
* Version Independent ID: c4652a23-abc2-63ed-11fa-334b0f46698a
* Content: [Extension des projets SQL Database - Azure Data Studio](https://docs.microsoft.com/fr-fr/sql/azure-data-studio/extensions/sql-database-project-extension?view=sql-server-ver15#feedback)
* Content Source: [docs/azure-data-studio/extensions/sql-database-project-extension.md](https://github.com/MicrosoftDocs/sql-docs.fr-fr/blob/live/docs/azure-data-studio/extensions/sql-database-project-extension.md)
* Product: **azure-data-studio**
* Technology: **azure-data-studio**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by dzsquared** [comment]
Hi @Churchill59  - we're absolutely looking into this and would love your feedback.  If you can, please share more about your scenario in the Azure Data Studio issues.  To make this even easier, if you'd prefer not to open a new issue, you can leave a comment here; https://github.com/microsoft/azuredatastudio/issues/11105

**Comment by dzsquared** [comment]
#please-close

**Comment by Churchill59** [comment]
Hello,

Actually it is fine I can push to Azure Devops and trigger a build pipeline. (though still struggling with the sensitivity statement that seems not supported in the azure devops built).

Thank you
