### ISSUE TITLE
Broken "Modifier" Link in doc page

### ISSUE THREAD

**Issue by glacasa** [MicrosoftDocs/sql-docs.fr-fr#7]
I was on this page : https://docs.microsoft.com/fr-fr/sql/sql-operations-studio/quickstart-sql-server

And I clicked on "Modifier" to correct a sentence. It opens a page to : https://github.com/MicrosoftDocs/sql-docs.fr-fr/blob/live/docs/sql-operations-studio/quickstart-sql-server.md , and returns a 404 error.

This repository seems to be empty, so I don't know where the french translation is stored, or how to submit corrections.

**Comment by CeciAc** [comment]
Hello @glacasa 
Thank you for your feedback.
The issue was fixed.
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
