### ISSUE TITLE
Mauvais nom de table

### ISSUE THREAD

**Issue by gzl** [MicrosoftDocs/sql-docs.fr-fr#92]
Correction de la désignation du nom de la table .
sql-docs.fr-fr\docs\relational-databases\replication\merge
Page : advanced-merge-replication-conflict-detection-and-resolution.md
line 120 :  **MSmerge_conflic_\<nom_publication>_\<nom_article>**
Correctif : **MSmerge_conflict_\<nom_publication>_\<nom_article>**

**Comment by CeciAc** [comment]
Bonjour, @gzl 
Merci pour votre feedback. 
Nous révisons activement vos commentaires et nous vous recontacterons bientôt. 
Cordialement, 
L’équipe Microsoft DOCS International

**Comment by CeciAc** [comment]
Bonjour @gzl  

Merci pour votre feedback. 

Notre équipe linguistique a examiné vos suggestions de traduction et les a acceptées. Nous avons modifié les articles concernés selon vos suggestions et les avons republiés sur les pages advanced-merge-replication-conflict-detection-and-resolution.md du site Docs.  

Votre contribution à nos articles est grandement appréciée. Nous vous encourageons donc à continuer d’envoyer vos commentaires à Microsoft. 

Cordialement, 
L’équipe Microsoft DOCS International
